name=Rednova Boards
version=2.4.0
author=Rednova
maintainer=Rednova
sentence=Controls the motors, buzzer, RGB LED, switches, button, and trimpot on Rednova boards.
paragraph=Provides the Arduino IDE API and examples for the Rednova V2 and Rednova Micro robot controller boards.
category=Device Control
architectures=avr
includes=Rednova.h
