name=Rednova Boards
version=1.0.2
author=Rednova
maintainer=Rednova
sentence=Controls the motors, buzzer, RGB LED, switches, button, and trimpot on Rednova boards.
paragraph=Provides a simple API and examples for Rednova V2, Rednova Mega, and Rednova Micro robot controller boards.
category=Device Control
architectures=avr
includes=Rednova.h
