name=Rednova Boards
version=2.0.0
author=Rednova
maintainer=Rednova
sentence=Controls the motors, buzzer, RGB LED, switches, button, and trimpot on Rednova boards.
paragraph=Provides the initial Arduino IDE API and examples for the Rednova V2 robot controller board.
category=Device Control
architectures=avr
includes=Rednova.h
